### ISSUE TITLE
OFR-607 Map Not Displaying

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#10]
**Describe the bug**
The map for OFR-607 (Glen Canyon Dam Area) 1:24k map does not display in the interactive map portal.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Glen Canyon Dam Area'
3. See that the map does not display.

**Expected behavior**
The map to be visible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by marshallrobinson** [comment]
This is a great map that needs to be added. There is a geotif in MapShelf that can be added to the 24k mosaic dataset.

**Comment by marshallrobinson** [comment]
Moving to all-inclusive issue...
