### ISSUE TITLE
Interactive Map: Wrong Map: OFR-541 (Temple Mountain Quad)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#12]
**Describe the bug**
The interactive map shows OFR-541 as the pencil-colored map, rather than the vector map shown in the report document.

**To Reproduce**
1. Go to 'https://geology.utah.gov/apps/intgeomap/'
2. Search for 'Temple Mountain'
3. View the PDF file
4. Compare the map on the last page in the PDF file to the map displayed in the interactive map viewer.

**Expected behavior**
To see the same map as in the map report. If there is a vectorized map available, to see that instead of a pencil-colored map.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by marshallrobinson** [comment]
Please change out the map in the mosaic dataset with OFR-541. If there is vector data, please use it. If not please use the tif file on MapShelf.

**Comment by marshallrobinson** [comment]
Moving to all-inclusive issue...
