### ISSUE TITLE
Basemap (Hillshade) Error: M-231 Virgin Quad

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#13]
**Describe the bug**
Gross error in how TIN and hillshade were produced (see attached image).

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Virgin Quad'
3. Scroll to the quad's northwest corner

**Expected behavior**
A hillshade that's representative of the topography.

**Screenshots**
<img width="230" alt="Screenshot 2021-05-24 152734" src="https://user-images.githubusercontent.com/84141184/119409471-99725f00-bca4-11eb-89fb-18e457346135.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by marshallrobinson** [comment]
I submitted an issue to ESRI today, hopefully they can get to this in the near future.
