### ISSUE TITLE
Interactive Map: Old Map Displayed: M-127

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#14]
**Describe the bug**
2002 OFR-386 map is displayed for the Kolob Arch quad in the interactive map instead of the 2007 M-217 map, both by Biek.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Kolob Arch'
3. In 'Map Downloads' mode, click on the Kolob Arch qudrangle and cycle between the OFR and M maps
4. Note that the 2002 map is displayed (evident by color choices and Quaternary units mapped on the western side of the quad)

**Expected behavior**
Visualize the most recent map, or be able to change between which map is displayed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by marshallrobinson** [comment]
@JP-GEO, please update the mosaic dataset with the newer, M-217 map.

**Comment by marshallrobinson** [comment]
Moving to consolidated issue
