### ISSUE TITLE
Interactive Map: Incorrect Search Term: M-208dm

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#15]
**Describe the bug**
Cannot find the 'Jordan Narrows' quadrangle by searching 'Jordan Narrows' -- searchable term is 'Jordan Narrow.'

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Jordan Narrows' and see that there are no results
3. Search for 'Jordan Narrow'
4. Note that the quad is called 'Jordan Narrows,' rather than 'Jordan Narrow.'

**Expected behavior**
To be able to query a map by its quad name.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by marshallrobinson** [comment]
fixed
