### ISSUE TITLE
Interactive Map: Inconsistent Search Terms

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#16]
**Describe the bug**
Some map searchable terms end with 'Quad' and other do not.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Enter 'Dairy' into map search bar.
3. See that recommended completion is 'Dairy Ridge.'
4. Enter 'Horse Ridge' into the map search bar.
5. See that recommended completion is 'Horse Ridge Quad.'

**Expected behavior**
Consistency.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by marshallrobinson** [comment]
fixed
