### ISSUE TITLE
Interactive Map: Missing Map: OFR-456

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#17]
**Describe the bug**
7.5' map OFT-456 (West Mountain Peak) does not display, though the map can still be selected and the PDF downloaded.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'West Mountain Peak'
3. See that the map can be downloaded, but is not drawn in the viewer.

**Expected behavior**
To see the map.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by marshallrobinson** [comment]
Not sure what happened to this quad. @JP-GEO, please check to see if we have a geotiff for this publication and add it to the mosaic dataset.

**Comment by marshallrobinson** [comment]
Moving to consolidated issue
