### ISSUE TITLE
Interactive Map: Incorrect Map Representation: M-194

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#18]
**Describe the bug**
Publication M-194 has two different quadrangle maps, each on different map plates. Only one of these is searchable and selectable under 'Map Downloads' mode (as the Clarkston Portage Quad) in the interactive map portal. The Clarkston Quad and Portage Quad are two different 7.5' quadrangles! The name of the publication was abused to functional detriment.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Clarkston Portage'
3. See that this quad is named the 'Portage & Clarkston' quad, which is different from the search term! (Also there is no 'Portage & Clarkston' quad -- this is the Clarkston Quad!)
4. Click on the 7.5' quad to the west.
5. See that only larger-scale quads can be selected here.

**Expected behavior**
I expect (a) for the searchable name to be the same as the quad name, (b) for a quad to be named the proper name, and (c) to be able to interact with the maps of two different quads independently of each other, even if they both link to the same publication.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
The Portage & Clarkston Quad were published together under the M-194 series_id. I created a footprint for the quad, but the issue still remains that there can/is only one record in the pubs db for this publication.

**Comment by Stefankirby** [comment]
@marshallrobinson Marshall can close this issue is fixed based discussion with DM and Mapping.
