### ISSUE TITLE
Interactive Map: Wrong Map: OFR-351 (Valley City)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#19]
**Describe the bug**
The map displaying the map portal is not the same as the map in the publication -- there are distinct differences in fill style, line work, and even units reported! Not sure where the map displayed in the interactive map portal came from, but it's not from this publication!

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Valley City'
3. View the map PDF
4. See that the map displayed in the interactive viewer is not the same as the map in PDF
5. See that the geoTIFF is the same as in the PDF and NOT that displayed in the interactive map viewer.
6. Note the same issue when searching for the map in 'geology.utah.gov/map-pub/publications/'

**Expected behavior**
The map available for download should be the same map displayed.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/84141184/119885521-2c063e80-beef-11eb-9f60-5b1e93834ac9.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
The one getting displayed in the map interface is USGS I-86. It's from 1955. The publication for download is OFR-351 from 1997. Please replace I-86 (the yellow one) with OFR-351 (the black/white one).

**Comment by marshallrobinson** [comment]
Moving to consolidated issue
