### ISSUE TITLE
Interactive Map: Incorrect Map Footprint: OFR-299 (Standardville Quad)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#20]
**Describe the bug**
Footprint of map OFR-299 (Standardville Quad) does not represent map extent.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Standardville'
3. See map footprint and compare with thumbnail of downloadable map

**Expected behavior**
Map footprint should reflect mapped extent.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/84141184/119894246-9a4ffe80-bef9-11eb-9f1f-d3a63ff9261a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
fixed
