### ISSUE TITLE
Interactive Map: Missing Map: OFR-324

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#21]
**Describe the bug**
Map does not display for OFR-324 (Washington Quad). May not exist as a georeferenced image.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Washington quad'
3. See that quad can be selected and downloaded (as PDF), but does not appear in the map viewer.

**Expected behavior**
The map to be visible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
I'm not sure why this quad isn't there. It may have never been there, so the image may still need georeferenced.

**Comment by marshallrobinson** [comment]
Moving to consolidated issue
