### ISSUE TITLE
Interactive Map: Wrong Map: OFR-301 (Steele Butte)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#23]
**Describe the bug**
Map only partially displays and is not the correct map (correct quad, but not this publication, and not mapping any other publication I can access for the quad in the interactive map).

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Steele Butte'
3. See that only the southern portion of the map displays.
4. Download map PDF.
5. See that the map in the PDF is the correct map (OFR-301) but not the one displayed in the interactive map viewer.

**Expected behavior**
The full map to be displayed.
The same map in the interactive viewer as the map I can download.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
This map needs to be checked in the mosaic dataset.

**Comment by marshallrobinson** [comment]
Moving to consolidated issue
