### ISSUE TITLE
Interactive Map: Missing Map: CR-92-8.2 (Tony Grove Creek)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#24]
**Describe the bug**
Map is selectable and downloadable (as a PDF), but does not appear in the interactive map.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Tony Grove'
3. See that the map can be searched, selected, and downloaded, but does not display

**Expected behavior**
The map to display.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Additional context**
Same problem with adjacent quad from same publication, CR-92-8.4.

**Comment by marshallrobinson** [comment]
Moving to consolidated issue
