### ISSUE TITLE
Interactive Map: Missing Map: CF-92-8.4 (Temple Peak)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#25]
**Describe the bug**
Map is selectable and downloadable (as a PDF), but does not appear in the interactive map.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Temple Peak'
3. See that the map can be searched, selected, and downloaded, but does not display

**Expected behavior**
The map to display.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Additional context**
Same problem with adjacent quad from same publication, CR-92-8.2.

**Comment by marshallrobinson** [comment]
This quad needs to be added to the mosaic dataset. May need to hunt down a decent geotif, or create a new one from the pdf.

**Comment by marshallrobinson** [comment]
Moving to consolidated issue
