### ISSUE TITLE
Interactive Map: Incorrect Map Extent: CR-92-8.3 (Mount Elmer)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#26]
**Describe the bug**
Map does not display to proper extent -- the full map displays, but does not stretch appropriately across the ground that it covers.\

Also, can't search by "Mount Elmer" -- need to search by "Mt. Elmer" or "Elmer"

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Mount Elmer'
3. See that there are no results
4. Search for 'Elmer'
5. See that map displays, but not at its proper extent (it's not cropped... it's corners are just wrong)

**Expected behavior**
Map displayed to proper extent.

Search quad by its proper name rather than by abbreviations.

**Screenshots**
![Screenshot 2021-06-02 112514](https://user-images.githubusercontent.com/84141184/120525335-43cd3f00-c395-11eb-9381-ef77615b7cd4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
Please try georeferencing this tif and adding it back to the mosaic dataset. Thanks

**Comment by marshallrobinson** [comment]
Moving to consolidated issue
