### ISSUE TITLE
Interactive Map: Incorrect Thumbnail: CI-132 (Petes Cove)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#33]
**Describe the bug**
Thumbnail to CI-132 in 'download' menu in interactive map is incorrect.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Petes Cove'
3. Click on the quadrangle in 'Download' mode
4. See that the thumbnail for the map is incongruent with the displayed map and the downloadable PDF.

**Expected behavior**
Thumbnail to indicate what I can expect to download.

**Screenshots**
![Screenshot 2021-06-03 090754](https://user-images.githubusercontent.com/84141184/120667944-37a3b900-c44b-11eb-9488-c80d06705507.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
fixed thumbnail
