### ISSUE TITLE
Interactive Map: Missing Map: OFR-130 (Antelope Peak)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#36]
**Describe the bug**
Interactive map does not display this map, though the quad is searchable, selectable, and downloadable.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Antelope Peak'
3. See that the map does not display

**Expected behavior**
The map to display.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
This is OFR-130. @JP-GEO, are you able to find this map to add to the Portal?

**Comment by marshallrobinson** [comment]
Moving to consolidated issue
