### ISSUE TITLE
Interactive Map: Limited Map Extent: I-1762 (Fort Douglas)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#38]
**Describe the bug**
Interactive map portal clips the map to the extent of the quad.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Fort Douglas'
3. Download map GeoTIFF
4. See that there are mapped areas outside of the quad boundaries

**Expected behavior**
The same map to be displayed as I can download.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
Technically correct, but I'm not sure we want to re-draw the official quadrangle boundary to match what was mapped. Others can chime in their opinions.
