### ISSUE TITLE
Interactive Map: Incorrect Display: M-90 (Mount Ellen)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#40]
**Describe the bug**
Only the southern portion of M-90 displays in the interactive map.
Also, the map can only be searched as 'Mt Ellen,' instead of 'Mount Ellen.'

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Ellen'
3. See that the quad's search term is 'Mt Ellen' instead of 'Mount Ellen'
4. See that the quad only partially displays

**Expected behavior**
The full map to be displayed.
The map to be searchable by its name, rather than by abbreviations

**Screenshots**
![Screenshot 2021-06-03 182321](https://user-images.githubusercontent.com/84141184/120727843-cd196a00-c498-11eb-94f7-60559cff7e65.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
The abbreviation was is removed.

@JP-GEO, can you figure out why the upper 2/3 of the map are not getting displayed please?
