### ISSUE TITLE
Interactive Map: Limited Map Extent: I-1606 (N Ogden and parts of Ogden and Plain City)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#41]
**Describe the bug**
Map extent is cropped to just the North Ogden quad.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'North Ogden and Plain'
3. See that the map does not fill the extent of its footprint

**Expected behavior**
A map to display at its full extent, filling its footprint

**Screenshots**
![Screenshot 2021-06-04 103646](https://user-images.githubusercontent.com/84141184/120834837-cc2c1b00-c520-11eb-92f3-70be6e06f831.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
this is expected because the parts that don't show up are superseded by new maps.
