### ISSUE TITLE
Interactive Map: Incorrect Search Term: I-1297 (Crater Springs)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#42]
**Describe the bug**
Not entirely sure if this is a bug, but the map can only be found by its quad name 'Crater Bench' and not by the name of the map 'Crater Springs,' making a map difficult to discover in the interactive map.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Crater'
3. Select 'Crater Bench'
4. See that the map is named 'Crater Springs'

**Expected behavior**
A map to be searchable by its name (and its quad name).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Additional context**
May want to search a map by its name, and may not know what quad it's located in, or the location of that quad. Vice-versa is true as well: May want to look up a map for a quad and not know what the name of the map is at that location.

**Comment by marshallrobinson** [comment]
fixed
