### ISSUE TITLE
Missing Maps: OF-81-...

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#43]
**Describe the bug**
Missing maps in interactive map and publication database.
* OF-81-718 (Mahogany Point)
* OF-81-1356 (Red Point)
* OF-81-319 (Ferron City)
* OF-81-612 (The Cap)

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/' or 'geology.utah.gov/apps/publications/'
2. Search for any of the above publications
3. See that the publications cannot be found

**Expected behavior**
Published maps to be accessible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Additional context**
These appear to USGS publications, available at the URLs:
* https://pubs.er.usgs.gov/publication/ofr81718
* https://pubs.er.usgs.gov/publication/ofr811356
* https://pubs.er.usgs.gov/publication/ofr81319
* https://pubs.er.usgs.gov/publication/ofr81612

**Comment by marshallrobinson** [comment]
Moving to consolidated issue.
