### ISSUE TITLE
Interactive Map and Publications: Bad PDF link: MF-1150

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#44]
**Describe the bug**
PDF link cannot be loaded for MF-1150-NE and MF-1150-SE, probably because they both try to link to a PDF title mf-1150.pdf, which does not seem to exist.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Sand Pass NE' or 'Sand Pass SE'
3. Attempt to download either map's PDF
5. Go to 'geology.utah.gov/apps/publications/'
6. Search for 'MF-1150'
7. Attempt to download either map's PDF
8. See error

**Expected behavior**
Be able to download the publication report(s) or map PDF(s).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
fixed
