### ISSUE TITLE
Interactive Map: Missing Map: MF-1150-SE (Sand Pass SE)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#45]
**Describe the bug**
Map footprint is selectable and map geotiff can be downloaded, but map does not appear in the interactive map.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Sand Pass SE'
3. See error

**Expected behavior**
The map to be visible in the interactive map.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Additional context**
MF-1150-SE shares a geotiff with MF-1150-NE. MF-1150-NE displays correctly in the interactive map.

**Comment by marshallrobinson** [comment]
Not sure where the map went for this in the mosaic dataset. There is still a geotif available for download if you can't find it in the regular geodata base, @JP-GEO. Otherwise, here is the geotif: https://ugspub.nr.utah.gov/publications/geotifs/24k/USGS_MF-1150_SandPassSE-Quads.zip
