### ISSUE TITLE
Map GeoTIFF not properly georeferenced: MF-1150-NE

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#46]
**Describe the bug**
Geotiff for MF-1150-NE can be downloaded, but is georeferenced for the other map on the same plate (MF-1150-SE), which is invalid for MF-1150-NE. There does not appear to be another viable geotiff for MF-1150-NE.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Sand Pass NE'
3. Download geotiff and display in ArcGIS

**Expected behavior**
Be able to download a geotiff for a quad and have it georeferenced for that quad.

**Screenshots**
![Screenshot 2021-06-08 143417](https://user-images.githubusercontent.com/84141184/121253675-a24b5f00-c866-11eb-9a09-40f26ec0a2a4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
Georeferenced properly.
