### ISSUE TITLE
Missing Maps: OF-80-491

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#47]
**Describe the bug**
Missing map in interactive map and publication database.
* OF-80-491 (Johns Peak)

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/' or 'geology.utah.gov/apps/publications/'
2. Search for the above publication
3. See that the publication cannot be found

**Expected behavior**
Published maps to be accessible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Additional context**
This map appears to be a USGS publications, available at 'https://pubs.er.usgs.gov/publication/ofr80491'

**Comment by marshallrobinson** [comment]
duly noted
