### ISSUE TITLE
Interactive Map: Incorrect Name: MF-1191 (Pole Mountain)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#48]
**Describe the bug**
The 'Pole Mountain' quad is searchable as, as displays in the downloads card as 'Pole Mountn'

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Pole'
3. See error

**Expected behavior**
Maps/quads to be searchable by their names, not by abbreviations, and for quads' proper names to appear in the map information/download card.

**Screenshots**
![Screenshot 2021-06-08 155059](https://user-images.githubusercontent.com/84141184/121262416-57831480-c871-11eb-9c6a-a3adca0ebb10.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
fixed
