### ISSUE TITLE
Interactive Map: Wrong Map Download: CI-82 (Emery West)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#49]
**Describe the bug**
Map shown in interactive map and thumbnail are correct, but the downloaded geotiff is for a 1931 map by Spieker.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Emery West'
3. Download the map geotiff
4. Compare geotiff to map displayed in interactive map and note its author and date

**Expected behavior**
Download the same map I see in the viewer.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
Hmm, the map being shown is CI-82. It can be found here: https://pubs.usgs.gov/coal/082/plate-1.pdf in case we don't have our own file somewhere still.

This is just a note to go with this bug: the current geotif being offered for download, though wrong, needs to be matched up with the proper record in the ugspubs database.

**Comment by marshallrobinson** [comment]
@JP-GEO, do we have this geotif file that's getting shown on the app somewhere?
