### ISSUE TITLE
Database Search Error

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#5]
**Describe the bug**
'Granite Mountain' quad (OFR-681dm) only searchable as 'Granite Mountn Quad' in interactive map portal.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap'
2. Search for 'Granite Mountain'
3. Note that there are no search results
4. Search for 'Granite'
5. See error that the search recommends 'Granite Mountn Quad'

**Expected behavior**
Should be able to find the 'Granite Mountain' quad by searching for 'Granite Mountain.'

**Screenshots**
![err_search](https://user-images.githubusercontent.com/84141184/118556113-b5b05200-b720-11eb-919d-bffda5b9e06c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by bw-young-ut** [comment]
Also note that the same issue occurs when searching in the map at 'https://geology.utah.gov/map-pub/maps/geologic-maps/', but not when searching the directory on the same page.

**Comment by marshallrobinson** [comment]
fixed
