### ISSUE TITLE
Interactive Map: Missing Map: OFR-15 (Lopers Spring)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#50]
**Describe the bug**
Quad is searchable and downloadable, but not visible in interactive map.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Lopers Spring'
3. See error

**Expected behavior**
Map to be visible in the interactive map.

**Screenshots**
![Screenshot 2021-06-09 104909](https://user-images.githubusercontent.com/84141184/121397095-4853a380-c911-11eb-8850-316160d7db2f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
Is this map possibly still in the archived geodatabase?

**Comment by marshallrobinson** [comment]
Moved to consolidated issue
