### ISSUE TITLE
Timpoweap Unit Description Update

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/geolMapPortal#51]
Coming from Grant's email: 

> When I click on the Timpoweap Member just east of Hurricane I get the following popup description.
> 
> TRmt: Timpoweap Member of the Moenkopi Formation (Lower Triassic)
> As described above, but mapped separately in the White Hills, Jarvis Peak, and Scarecrow Peak quadrangles, and locally along the Hurricane Cliffs.
> 
> That might work in the booklet DOMU or attributes but it doesn't work for the Portal.  Unfortunately, we didn't have the concept down back a few years ago.
> 
> There is a good description for Timpoweap in the St George 30x60 booklet.  Please replace the old description with this one: 
> 
> TRmt Timpoweap Member (Lower Triassic) – Lower part
> consists of light-brown-weathering, light-gray to grayish orange, thin- to thick-bedded limestone and cherty
> limestone; chert occurs as small disseminated blebs,
> thus giving weathered surfaces a rough texture; upper
> part consists of grayish-orange, thin- to thick-bedded,
> slightly calcareous, fine-grained sandstone, siltstone, and
> mudstone; both parts form low cliffs and ledges and form
> a gently undulating surface on top of the Permian-Triassic
> unconformity; upper contact with the lower red member
> is conformable and gradational and corresponds to a
> change from yellowish-brown, fine-grained sandstone,
> siltstone, and minor limestone below to reddish-brown
> siltstone and mudstone above (Biek, 2003b, 2007a);
> deposited in a shallow-marine environment (Nielson and
> Johnson, 1979; Dubiel, 1994; Lucas and others, 2007);
> Lucas and others (2007) reported a late Smithian age
> for the unit and reiterated a correlation with the Sinbad
> Limestone of central and eastern Utah; ranges from 50 to
> 180 feet (15–55 m) thick (Nielson, 1981).

**Comment by marshallrobinson** [comment]
Not a high-priority if you're busy with other things. 

Thanks!

**Comment by annafarb** [comment]
Started working on this in the 30x60 mxd
For St. George I changed the description to the one Grant provided above.

I was checking the surrounding quads and in Kanab, this is the description for TRmt:

Light gray-brown limestone, dolomite, sandstone, cherty breccia, and siltstone; thin- to thick-bedded; some sandstone beds are pebbly; upper half is more resistant and forms a cliff over a ledgy lower part; locally a thin section of tan and brown siltstone (Black Dragon Member?) underlies the unit; contact with Kaibab Formation below is an unconformity; 6 to 15 m (20-50 ft) thick at exposures on Buckskin Mountain in the southeast part of the quadrangle; well data indicate the Timpoweap may be as much as 45 m (150 ft) thick in part of the quadrangle.

Thoughts? Should I update that one as well?

**Comment by annafarb** [comment]
Anyways, looks like that unit is already updated without having to publish/cache  :D
