### ISSUE TITLE
Interactive Map: Bad Map: I-833 (Tintic Mountain and part of McIntyre)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#52]
**Describe the bug**
Map can be searched in the interactive map, but (a) has a typo in the search term, (b) does not display, and (c) has no 'downloads' card information.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'tintic'
3. Select the 'Tintic Moutnain - Part Mcintyre Quads' option in the search drop-down

**Expected behavior**
A map to be discoverable by its proper name, visible, and downloadable.

**Screenshots**
![Screenshot 2021-06-09 130410](https://user-images.githubusercontent.com/84141184/121414127-996c9300-c923-11eb-833e-33b24d82cc66.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Additional context**
The map can be found by searching for 'I-833' in 'geology.utah.gov/apps/publications/', but the access option is to purchase a hard copy. This map may not exist in digital format.

**Comment by marshallrobinson** [comment]
Fixed by adding quad name to MySQL and editing Footprint name
