### ISSUE TITLE
Interactive Map: Wrong Map?: MF-521 (Skutumpah Creek)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#53]
**Describe the bug**
Interactive displays a color-pencil-filled version of MF-521 that lacks the structural contours. The origin of the pencil-colored map is unclear.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Skutumpah'
3. View the map's PDF
4. See the inconsistency

**Expected behavior**
Download the same map as the one that is visualized, or visualize the same map that is downloaded, or, better yet, be able to choose between them.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.77

**Comment by marshallrobinson** [comment]
Will need to find MF-521 geotif.
-Is the geotif that matches what is found in the archival geodatabase? https://ugspub.nr.utah.gov/publications/united_states_geological_survey/geologic_maps/mf/mf-521.pdf

**Comment by marshallrobinson** [comment]
moved
