### ISSUE TITLE
Willard Quad (M-278dm) getting covered by Mantua part Willard Quad (I-1605)

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/geolMapPortal#56]
Please edit the clipping mask of the 24k Mosaic Dataset so that the Mantua and Part of Willard Quad (I-1605) doesn't overlap the newer Willard Quad (M-278dm). 

Don't edit the footprint of Mantua and Part of Willard Quad (I-1605) in the footprint service though.

Thanks

**Comment by annafarb** [comment]
Ok! should be good now.
