### ISSUE TITLE
Interactive Map: Wrong Map: MF-150 (Lisbon Gap)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#57]
**Describe the bug**
The map displayed in the interactive map viewer is not the same as is visible in the downloadable PDF -- the displayed map lacks topographic contours, structure contours, and various contacts.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Lisbon Gap'
3. Open the map's PDF
4. See that the two maps are different, verify that the PDF map is correct (marked MF-150 in the bottom-left corner)

**Expected behavior**
The same map to displayed as can be downloaded.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Comment by marshallrobinson** [comment]
Need to figure out where the MF-150 geotif is. The older I-157 map is showing and is the one available for download.

**Comment by marshallrobinson** [comment]
moving to consolidated issue
