### ISSUE TITLE
Interactive Map: Bad PDF Link: I-280 (Factory Butte)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#58]
**Describe the bug**
Get '404 - File or directory not found' when trying to download the PDF for Factory Butte (I-280) from the interactive map.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Factory Butte'
3. Attempt to download the quad's PDF

**Expected behavior**
Access the quad's PDF file.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Comment by marshallrobinson** [comment]
fixed
