### ISSUE TITLE
Display Irregular (Non-Quad) Maps in Interactive Geologic Map Portal

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#6]
**Is your feature request related to a problem? Please describe.**
in 'geology.utah.gov/apps/intgeomap/' I can search for a map with an irregular boundary (MP-17-2dm, Central Mineral Mountains), but it does not display. It has GIS data, but I expect that the lack of display is because only regular quads are supposed to display.

**Describe the solution you'd like**
An option to choose which map is displayed, or to toggle display of maps overlapping the viewport extent, including irregular maps.

**Describe alternatives you've considered**
Just show the irregular map where there isn't a quad available.

**Additional context**
![irreg_map_display](https://user-images.githubusercontent.com/84141184/118682202-771ca500-b7bd-11eb-9ac4-b4adb7932b4d.png)

**Comment by bw-young-ut** [comment]
Upgrade this to a BUG -- clicking in the Central Mineral Mountains map area in 'Unit Descriptions' mode yields information from the 1:24k map, but that map doesn't display!

**Comment by marshallrobinson** [comment]
@JP-GEO, please add the GIS vector data to the 24k map service. The geodatabase for this map is on the server; is it still in the 7.5k ArcPro project and not showing up for some reason?

**Comment by marshallrobinson** [comment]
Moving to all-inclusive issue...
