### ISSUE TITLE
Interactive Map: Wrong Map Information: I-32 (Chippean Rocks/Elk Ridge)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#60]
**Describe the bug**
Map I-32 says that it is the 1959 Lewis map (MF-200), but it's the 1955 Hackman map.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Chippean'
3. Download and view the geotiff
4. See the discrepancy between the map info card and the information on the bottom of the map.

**Expected behavior**
Correct information for the map that's accessible, or access to the map referenced in the information card.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Comment by marshallrobinson** [comment]
fixed
