### ISSUE TITLE
Interactive Map: Wrong Map: MF-148 (Sop Canyon)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#61]
**Describe the bug**
The map displayed in the interactive map is not the 1958 map by Weir and Dodson. The thumbnail and geotiff are correct, though.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Sop Canyon'
3. Download and view the geotiff.
4. See discrepancy

**Expected behavior**
The same map to be in the viewer as indicated in the map's information card and downloadable geotiff.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Additional context**
A lot of these older MF-series maps cover some of the same area with even older I-series USGS (Uranium, I think) maps. The quad just to the east (I-176) is in the same style as the map displayed in the interactive map viewer for MF-148. The publications database seems to only have one of these maps (the I-series or MF-series) for each relevant quadrangle... not both.

**Comment by marshallrobinson** [comment]
Is USGS_MF-148_SopCynQuad still in the archived geodatabase?

**Comment by marshallrobinson** [comment]
moving to consolidated issue
