### ISSUE TITLE
Interactive Map: Wrong Map: MF-193 (Poison Canyon)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#62]
**Describe the bug**
The map displayed in the interactive map is the 1958 map by Lewis and Campbell. The thumbnail and geotiff are correct, though.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Poison Canyon'
3. View the PDF.
4. See discrepancy

**Expected behavior**
The same map to be in the viewer as indicated in the map's information card and downloadable PDF/geotiff.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Additional context**
A lot of these older MF-series maps cover some of the same area with even older I-series USGS (Uranium, I think) maps. The publications database seems to only have one of these maps (the I-series or MF-series) for each relevant quadrangle... not both.

**Comment by marshallrobinson** [comment]
@JP-GEO, is the MF-193_PoisonCynQuad geotif file still in the archived geodatabase? If so, go ahead and replace the current I-series map that's displayed.

**Comment by marshallrobinson** [comment]
moving to consolidated issue
