### ISSUE TITLE
Interactive Map: Missing Map: MF-112 (Notom)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#63]
**Describe the bug**
Map does not display in the interactive map portal, though the quad is searchable and selectable.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Notom Quad'
3. See error

**Expected behavior**
A map to be visible in the map portal.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Comment by marshallrobinson** [comment]
Interesting, @JP-GEO, is this quad still in the archived geodatabase by chance?

**Comment by marshallrobinson** [comment]
moved
