### ISSUE TITLE
Interactive Map: Incorrect Search Term: MF-110 (Deer Creek Lake)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#64]
**Describe the bug**
Map for MF-110 (Deer Creek Lake Quad) cannot be searched with 'Deer Creek Lake Quad', but by 'Deer Lake Quad'

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Deer Creek Lake'
3. See that there are no search results
4. Search for 'Deer Lake'
5. That the name of the quad does not match the search term

**Expected behavior**
Be able to discover a quad by its name.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Comment by marshallrobinson** [comment]
fixed
