### ISSUE TITLE
Interactive Map: Incorrect Footprint: I-196 (Water Pockets)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#67]
**Describe the bug**
Map footprint does not represent map extent.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Water Pockets Quad'
3. See error

**Expected behavior**
Map extent to be accurately represented in the interactive map.

**Screenshots**
![Screenshot 2021-06-14 112945](https://user-images.githubusercontent.com/84141184/121933876-d958bf00-cd03-11eb-9d2c-4063b405f0b1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Comment by marshallrobinson** [comment]
fixed
