### ISSUE TITLE
Interactive Map: Incorrect Search Term: I-120 (Sids Mountain)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#68]
**Describe the bug**
Map's search term uses abbreviation 'mountn' instead of 'mountain,' making it not searchable by the quad's proper name.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Sids'
3. See error

**Expected behavior**
The quad/map to be discoverable by its name.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Comment by marshallrobinson** [comment]
Fixed it
