### ISSUE TITLE
Interactive Map: Missing Map: I-82 (Shay Mountain)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#69]
**Describe the bug**
Map I-82 doesn't display -- MP-06-7dm (Abajo Mountains) is displayed instead.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for 'Shay Mountain'
3. See discrepancy

**Expected behavior**
To have the same map visible as can be downloaded, or to choose between multiple valid maps for a quad if more than one exists for a particular scale range.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.101

**Comment by marshallrobinson** [comment]
@JP-GEO, Abajo Mountains can be removed and archived from the MD_24K service because the vector version of Abajo Mts already exists in the 24K_Quads service.

**Comment by marshallrobinson** [comment]
moving to consolidated issue
