### ISSUE TITLE
Incorrect Map Displayed

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#7]
**Describe the bug**
'geology.utah.gov/apps/intgeomap/' displays wrong (correct, but outdated) map for MP-16-2dm Donkey Flat quad.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap/'
2. Search for and navigate to 'Donkey Flat quad'
3. Download the map PDF
4. See that the thumbnail and displayed map are incorrect

**Expected behavior**
Expect to see the same map as I download, which should be the most recent map for the quad.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by marshallrobinson** [comment]
Please replace the old raster with the new raster. New raster can be grabbed from MapShelf or downloaded from the web app.

**Comment by marshallrobinson** [comment]
Moving to all-inclusive issue...
