### ISSUE TITLE
Wrong GIS Data

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#71]
**Describe the bug**
Attempting to download GIS data for OFR-703dm yields the GIS data for OFR-678dm.

**To Reproduce**
1. Go to 'https://geology.utah.gov/map-pub/maps/geologic-maps/#geomaptable'
2. Search for 'OFR-703dm' and download its GIS data
3. Search for 'OFR-678dm' and download its GIS data
4. Load shapefiles or geodatabase for both in ArcGIS
5. See that they are the same

**Expected behavior**
Be able to download the GIS data for the map.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.106

**Comment by marshallrobinson** [comment]
![image](https://user-images.githubusercontent.com/5225390/160917472-c886b81f-89ee-4778-afbf-246fa4b35b0f.png)

I see the correct data...
