### ISSUE TITLE
Missing GIS Data: MP-16-1

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#72]
**Describe the bug**
The downloadable GIS data for map MP-16-1 (Kelton Pass SW-Monument Peak SW)... contains no map GIS data.

**To Reproduce**
1. Go to 'https://geology.utah.gov/map-pub/maps/geologic-maps/'
2. Search for 'mp-16-1'
3. Download GIS data
4. See that the ZIP archive contains no GIS data (the .mxd only seems to contain cartography and basemap layers, not actual map data)

**Expected behavior**
GIS data to be in the GIS data download.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.106

**Comment by marshallrobinson** [comment]
![image](https://user-images.githubusercontent.com/5225390/160915022-b2db8c47-00b1-4514-935b-964ef1ee393c.png)


I see a full GIS-created geologic map.
