### ISSUE TITLE
Bad GIS ZIP - MP-171dm (Swallow Canyon)

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#74]
**Describe the bug**
The ZIP containing the quad's GIS data appears to be invalid or corrupted.

**To Reproduce**
1. Go to 'https://geology.utah.gov/map-pub/maps/geologic-maps/' or 'https://geology.utah.gov/apps/intgeomap/'
2. Search for 'MP-171' or 'Swallow Canyon'
3. Download the GIS data.
4. Attempt to access the ZIP file.
5. See error: "The Compressed (zipped) Folder '[...]\mp-171.zip' is invalid."
6. Attempt to extract files:
7. See error: "Cannot Complete the Compressed (zipped) Folders Extraction Wizard" because "The compressed (zipped) folder is empty" (unlikely, though, since it's 522,168 KB).

**Expected behavior**
Be able to download and access the GIS data.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.124

**Comment by marshallrobinson** [comment]
Multiple people do not have this experience.
