### ISSUE TITLE
Interactive Map - Missing Map Information/Downloads - M-283dm - SLC South

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#75]
**Describe the bug**
Can view and see unit descriptions for the Salt Lake City South quadrangle, but cannot be select to view map information or download files.

**To Reproduce**
1. Go to 'https://geology.utah.gov/apps/intgeomap/'
2. Search for 'Salt Lake City South'
3. See that the information card is empty.
4. Attempt to select the quadrangle and cycle through maps intersecting the clicked location.
5. See that the map's information is not accessible

**Expected behavior**
Be able to view and download information and data associated with maps visible in the interactive map portal.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.124

**Comment by adammckean** [comment]
This is still an issue. The Salt Lake City South quadrangle is still not available as a download on the Interactive Geologic Map. The map is visible with the other 24k maps and the unit descriptions come up when selected but the map download option does not show Salt Lake City South as an option to download.

**Comment by marshallrobinson** [comment]
Go ahead and give it a try again @adammckean, it should be working now. The join between a couple of databases wasn't functioning properly because of case sensitivity.

**Comment by adammckean** [comment]
Yes that works now. Thank you.
