### ISSUE TITLE
I Think [this cool thing] Would be a Great Addition to the Application

### ISSUE THREAD

**Issue by ZWAnderson** [UGS-GIO/geolMapPortal#78]
### Why do you feel this application needs what you're requesting?
I know I've suggested this before but I think it's been enough time that I can be a pest and suggest it again: Keep the view the same when scrolling through the map download options rather than zooming to each footprint. It's really distracting (and annoying) when you scroll through the download options and get moved from the area you were looking at. 
Just my two cents. 
Thanks for being open to suggestions. 
And thanks for all the work behind this app - it's awesome and gets better with every update. 

### Describe the solution you'd like and why it builds value

Don't have the map move

### What impact will this new functionality have on this application's audience?

It won't drive people crazy when the map moves

### How Urgent is this?

High

### Please provide additional evidence from other users to support medium and high ranking

Adam wants the same thing

**Comment by marshallrobinson** [comment]
Give the new map-release a try and see if this is taken care of for you.

**Comment by ZWAnderson** [comment]
Brilliant! This is great. Thank you for working that in.

- Zach


*Zachary W Anderson *(*he/him/his*)
Geologist
Utah Geological Survey
Mapping Program
Phone (o):801-537-3300
Phone (c):801-330-7879
1594 W. North Temple
Suite 3110
Salt Lake City, UT 84116
