### ISSUE TITLE
I Think [adding the historical topo series as a base map option] Would be a Great Addition to the Application

### ISSUE THREAD

**Issue by ZWAnderson** [UGS-GIO/geolMapPortal#79]
### Why do you feel this application needs what you're requesting?

1) The historical topo map series provides more detailed topography
2) Easier to read/visualize marker contours
3) Immensely better place name information (creeks/canyons/peaks, etc.) 
4) More frequent contour labels
5) More feature rich-map (springs, infrastructure, mines, adits, etc.)

### Describe the solution you'd like and why it builds value

I suggest you have this as a fourth basemap option. Call it "historical topo" or something appropriate. Being able to see the geology in relation to all the reasons I listed above are why it will add value. 

### What impact will this new functionality have on this application's audience?

It will make me happy. I'm an audience. College profs would always say not to be afraid to ask questions because if one person is thinking it, you know there are more out there with the same question. I'm voicing this for the silenced masses who don't know that they can pester you all with requests. 

### How Urgent is this?

High

### Please provide additional evidence from other users to support medium and high ranking

This ain't fake news; This is eveedenced based scientology thtll make erry1 lerns the roks bettr.

**Comment by marshallrobinson** [comment]
Thanks for the suggestion Zach, and kudos for the creative responses :).
Much appreciated.

**Comment by lance-weaver** [comment]
What if we had a drop down in the Map Configuration Pane that allowed the user to select any of the available esri basemaps?

**Comment by ZWAnderson** [comment]
Hi  Lance,
Sure, that works. I believe the USA Topo maps option from ESRI is, for the
most part, made from the historical series.
I ask for this option because the historical topo maps are commonly much
more data-rich than the newer US-topo series or other composite topo base
options from ESRI. The historical series shows more names of mines,
springs, peaks, canyons, ect, which can be particularly helpful when trying
to find locations referenced in older reports.
 Thanks
- Zach


*Zachary W Anderson *(*he/him*)
Mapping Geologist,  P.G.
Utah Geological Survey
Geologic Mapping & Paleontology Program
Phone (o):801-537-3300
Phone (c):801-330-7879
1594 W. North Temple
Suite 3110
Salt Lake City, UT 84116

**Comment by Stefankirby** [comment]
@marshallrobinson @lance-weaver this is complete and can be closed based on group discussion.
