### ISSUE TITLE
Steves Mountain Quad Search Error

### ISSUE THREAD

**Issue by bw-young-ut** [UGS-GIO/geolMapPortal#8]
**Describe the bug**
Can only search for 'Steves Mountain' by 'Steves Mtn'.

**To Reproduce**
1. Go to 'geology.utah.gov/apps/intgeomap'
2. Search for 'Steves Mountain'
3. Note that there are no search results
4. Search for 'Steves'
5. See that the quad can be found by the name 'Steves Mtn'

**Expected behavior**
I would expect to find this quad by searching its name, not barred by abbreviations. Better yet would be to have 'Mountain' and 'Mtn' to be linked as equivalent in an ontological graph, but I expect that this querying system doesn't utilize ontologies.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by marshallrobinson** [comment]
fixed
