### ISSUE TITLE
BUG: [Baileys Lake display is weird]

### ISSUE THREAD

**Issue by ZWAnderson** [UGS-GIO/geolMapPortal#80]
### What happened?

1. Zoomed into the Baileys Lake quad
2.
3.

### What did you expect to happen?

I expected the labels to be correct and the transparency and appearance to match the surrounding newer quads. All the fault labels are really whacky. They are fine on the pdf version of the map, but messed up here. https://geology.utah.gov/apps/intgeomap/?view=scene&scale=20128&zoom=14.84&lat=40.76211&lng=-112.02546&layers=24k%2Cfootprints&tilt=1&heading=1&elev=7327&exag=2.5&base=ustopo

### Browser Version

Chrome

**Comment by marshallrobinson** [comment]
Thanks Zach, I did a little digging to see what is going on, and I figure out where the error is. I'll have Jessie take care of this.
