### ISSUE TITLE
Could you add commenting access to geolMapPortal for all mapping folks who do not have it?           I Think [this cool thing] Would be a Great Addition to the Application

### ISSUE THREAD

**Issue by Stefankirby** [UGS-GIO/geolMapPortal#83]
### Why do you feel this application needs what you're requesting?

I keep getting comments from people for tweaks fixes to the map portal.

I would like them to be able to comment -request stuff directly.

### Describe the solution you'd like and why it builds value

It saves significant time and generates so much value.

### What impact will this new functionality have on this application's audience?

Yes,  fixing problems benefits all.

### How Urgent is this?

Medium

### Please provide additional evidence from other users to support medium and high ranking

Please include Don Clark, Adam McKean, Rosemary Faselin, Bob Beik, and Grant Willis, and Kent Brown

**Comment by marshallrobinson** [comment]
Getting back from vacay today. I'll send out invites in the coming week.

**Comment by marshallrobinson** [comment]
I sent out invites today. 
@Stefankirby, did you happen to tell them that an invite would be coming? If not, I can send an email to let them know what to expect.

**Comment by Stefankirby** [comment]
If you could send a summary email about this that would be great.  Some folks won't connect with the GitHub email setup without a little more background.

Thanks
