### ISSUE TITLE
Missing DOI page for CI-131, Ship Mountain Point quad

### ISSUE THREAD

**Issue by RosieUtah** [UGS-GIO/geolMapPortal#90]
*@marshallrobinson I tried to put this in the Publications repo but it wouldn't let me submit*

1. Searched for Ship Mountain Point quad
2. Clicked on the download button under the Data column
3. Looked at pop up and didn't see link to DOI page
4. Expect to see link to DOI page in pop up

![image](https://user-images.githubusercontent.com/30906748/230137568-0774434d-90b4-47a5-b4dc-3a779963a985.png)

**Comment by marshallrobinson** [comment]
Since CI-131 is a USGS quadrangle, and we do not have the DOI link in our publications database, we are unable to display the DOI link at this time. Here is a DOI link to the USGS's landing page for you though: 10.3133/coal131
